### ISSUE TITLE
Missing dependency on "packaging"

### ISSUE THREAD

**Issue by mikedep333** [rsinger86/django-lifecycle#101]
Our application (Pulp 3, aka pulpcore) is failing with this error:

```
Traceback (most recent call last):
  File "/usr/local/lib/pulp/bin/pulpcore-manager", line 8, in <module>
    sys.exit(manage())
  File "/usr/local/lib/pulp/lib/python3.9/site-packages/pulpcore/app/manage.py", line 11, in manage
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/pulp/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/pulp/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "/usr/local/lib/pulp/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/pulp/lib/python3.9/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/usr/local/lib/pulp/lib/python3.9/site-packages/django/apps/config.py", line 301, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/lib/pulp/lib/python3.9/site-packages/pulpcore/app/models/__init__.py", line 4, in <module>
    from .base import (  # noqa
  File "/usr/local/lib/pulp/lib/python3.9/site-packages/pulpcore/app/models/base.py", line 9, in <module>
    from django_lifecycle import LifecycleModel
  File "/usr/local/lib/pulp/lib/python3.9/site-packages/django_lifecycle/__init__.py", line 1, in <module>
    from .django_info import IS_GTE_1_POINT_9
  File "/usr/local/lib/pulp/lib/python3.9/site-packages/django_lifecycle/django_info.py", line 1, in <module>
    from packaging.version import Version
ModuleNotFoundError: No module named 'packaging'
```

Manually installing `packaging` fixes it.

Perhaps it should be listed in install_requires?:
https://github.com/rsinger86/django-lifecycle/blob/master/setup.py#L56

**Comment by rsinger86** [comment]
Ugh, sloppy of me.

Thank you for noticing this. It's fixed in the latest release.

**Comment by mikedep333** [comment]
Thank you for fixing this quickly!
